- hosts: production
  remote_user: vagrant
  vars:
    app_name: my_geonode
    github_user: allspatial
    server_name: 192.168.56.151
    deploy_user: vagrant
  roles:
     - { role: ortelius.geonode }
